import type { InteractionResult, Severity } from "./types";

export type Drug = {
  name: string;
  aliases: string[];
  className: string;
  popular?: boolean;
};

export const DRUGS: Drug[] = [
  { name: "Warfarin", aliases: ["coumadin", "jantoven"], className: "Vitamin K antagonist", popular: true },
  { name: "Aspirin", aliases: ["acetylsalicylic acid", "asa"], className: "Antiplatelet / NSAID", popular: true },
  { name: "Ibuprofen", aliases: ["advil", "nurofen"], className: "NSAID", popular: true },
  { name: "Simvastatin", aliases: ["zocor"], className: "HMG-CoA reductase inhibitor", popular: true },
  { name: "Clarithromycin", aliases: ["biaxin"], className: "Macrolide antibiotic", popular: true },
  { name: "Metformin", aliases: ["glucophage"], className: "Biguanide", popular: true },
  { name: "Lisinopril", aliases: ["zestril"], className: "ACE inhibitor", popular: true },
  { name: "Sertraline", aliases: ["zoloft"], className: "SSRI", popular: true },
  { name: "Tramadol", aliases: ["ultram"], className: "Opioid analgesic" },
  { name: "Amiodarone", aliases: ["cordarone"], className: "Class III antiarrhythmic" },
  { name: "Digoxin", aliases: ["lanoxin"], className: "Cardiac glycoside" },
  { name: "Omeprazole", aliases: ["prilosec"], className: "Proton pump inhibitor" },
  { name: "Atorvastatin", aliases: ["lipitor"], className: "HMG-CoA reductase inhibitor" },
  { name: "Clopidogrel", aliases: ["plavix"], className: "P2Y12 inhibitor" },
  { name: "Amlodipine", aliases: ["norvasc"], className: "Calcium channel blocker" },
  { name: "Levothyroxine", aliases: ["synthroid"], className: "Thyroid hormone" },
  { name: "Furosemide", aliases: ["lasix"], className: "Loop diuretic" },
  { name: "Prednisone", aliases: [], className: "Corticosteroid" },
  { name: "Fluconazole", aliases: ["diflucan"], className: "Azole antifungal" },
  { name: "Ciprofloxacin", aliases: ["cipro"], className: "Fluoroquinolone" },
  { name: "Paracetamol", aliases: ["acetaminophen", "tylenol"], className: "Analgesic / antipyretic" },
  { name: "Spironolactone", aliases: ["aldactone"], className: "Potassium-sparing diuretic" },
];

export const POPULAR_DRUGS = DRUGS.filter((d) => d.popular).map((d) => d.name);

const key = (a: string, b: string) => [a.toLowerCase(), b.toLowerCase()].sort().join("|");

const WARFARIN_ASPIRIN: InteractionResult = {
  drugA: "Warfarin",
  drugB: "Aspirin",
  severity: "major",
  headline: "Additive bleeding risk through two independent pathways",
  summary:
    "Warfarin thins the blood by blocking vitamin K recycling, while aspirin permanently switches off platelet stickiness. Used together, the body loses both of its main ways to stop a bleed, so even small injuries can bleed much longer than expected.",
  mechanism: [
    { id: "m1", kind: "drug", label: "Warfarin + Aspirin", detail: "Two anticoagulant mechanisms taken at the same time." },
    { id: "m2", kind: "enzyme", label: "VKORC1 & COX-1", detail: "Warfarin inhibits VKORC1; aspirin irreversibly acetylates COX-1." },
    { id: "m3", kind: "protein", label: "Clotting factors II, VII, IX, X & thromboxane A2", detail: "Factor synthesis falls while platelet aggregation is blocked." },
    { id: "m4", kind: "interaction", label: "Pharmacodynamic synergy", detail: "Effects add up rather than cancel; aspirin also displaces warfarin from albumin." },
    { id: "m5", kind: "outcome", label: "Prolonged, hard-to-stop bleeding", detail: "Raised INR with impaired primary haemostasis — GI and intracranial bleeds dominate reports." },
  ],
  socImpacts: [
    {
      socId: "blood",
      severity: "contraindicated",
      explanation:
        "Clotting factor production drops while platelets can no longer clump, so both stages of clot formation fail at once.",
      symptoms: ["Easy bruising", "Nosebleeds", "Prolonged bleeding from cuts", "Anaemia"],
      evidence: ["DrugBank DB00682", "FAERS 12,480 reports", "PubMed 21245095"],
      confidence: 96,
    },
    {
      socId: "gi",
      severity: "major",
      explanation:
        "Aspirin strips the protective prostaglandin lining of the stomach while warfarin prevents any small erosion from sealing.",
      symptoms: ["Black or tarry stools", "Stomach pain", "Vomiting blood"],
      evidence: ["DDInter DDI-0031", "OpenFDA label warning"],
      confidence: 92,
    },
    {
      socId: "nervous",
      severity: "major",
      explanation: "Intracranial haemorrhage risk roughly doubles compared with warfarin alone.",
      symptoms: ["Sudden severe headache", "Confusion", "Weakness on one side"],
      evidence: ["PubMed 25569513", "FAERS 1,204 reports"],
      confidence: 84,
    },
    {
      socId: "vascular",
      severity: "moderate",
      explanation: "Haemorrhage at any vascular bed becomes more likely, including retroperitoneal bleeds.",
      symptoms: ["Haematoma", "Low blood pressure", "Dizziness on standing"],
      evidence: ["DrugBank interaction record"],
      confidence: 78,
    },
    {
      socId: "renal",
      severity: "moderate",
      explanation: "Aspirin reduces renal prostaglandins, lowering filtration and slowing warfarin clearance.",
      symptoms: ["Blood in urine", "Reduced urine output", "Swelling"],
      evidence: ["PubMed 19453914"],
      confidence: 66,
    },
    {
      socId: "investigations",
      severity: "major",
      explanation: "INR climbs above target within days; haemoglobin can fall silently.",
      symptoms: ["INR > 4.0", "Falling haemoglobin", "Raised bleeding time"],
      evidence: ["OpenFDA label", "DDInter DDI-0031"],
      confidence: 90,
    },
    {
      socId: "skin",
      severity: "minor",
      explanation: "Superficial capillary bleeding shows up as widespread bruising and petechiae.",
      symptoms: ["Petechiae", "Purpura", "Slow wound healing"],
      evidence: ["FAERS 620 reports"],
      confidence: 71,
    },
    {
      socId: "surgical",
      severity: "major",
      explanation: "Any procedure carries a substantially higher perioperative bleeding risk.",
      symptoms: ["Excess surgical bleeding", "Delayed haemostasis"],
      evidence: ["PubMed 22315265"],
      confidence: 80,
    },
  ],
  graph: {
    nodes: [
      { id: "warfarin", label: "Warfarin", kind: "drug" },
      { id: "aspirin", label: "Aspirin", kind: "drug" },
      { id: "vkorc1", label: "VKORC1", kind: "protein" },
      { id: "cox1", label: "COX-1", kind: "protein" },
      { id: "cyp2c9", label: "CYP2C9", kind: "gene" },
      { id: "liver", label: "Liver", kind: "organ", socId: "hepatobiliary" },
      { id: "platelets", label: "Platelets", kind: "organ", socId: "blood" },
      { id: "stomach", label: "GI mucosa", kind: "organ", socId: "gi" },
      { id: "bleed", label: "Major haemorrhage", kind: "effect", socId: "blood" },
      { id: "ulcer", label: "GI ulceration", kind: "effect", socId: "gi" },
    ],
    edges: [
      { from: "warfarin", to: "vkorc1", label: "inhibits" },
      { from: "warfarin", to: "cyp2c9", label: "metabolised by" },
      { from: "cyp2c9", to: "liver" },
      { from: "vkorc1", to: "liver", label: "factor synthesis" },
      { from: "aspirin", to: "cox1", label: "acetylates" },
      { from: "cox1", to: "platelets" },
      { from: "cox1", to: "stomach" },
      { from: "liver", to: "bleed" },
      { from: "platelets", to: "bleed" },
      { from: "stomach", to: "ulcer" },
      { from: "ulcer", to: "bleed" },
    ],
  },
  effectsA: [
    { name: "Bleeding", socId: "blood", frequency: "common" },
    { name: "Bruising", socId: "skin", frequency: "common" },
    { name: "Raised INR", socId: "investigations", frequency: "common" },
    { name: "Hair loss", socId: "skin", frequency: "uncommon" },
    { name: "Purple toe syndrome", socId: "vascular", frequency: "rare" },
    { name: "Liver enzyme elevation", socId: "hepatobiliary", frequency: "uncommon" },
  ],
  effectsB: [
    { name: "Bleeding", socId: "blood", frequency: "common" },
    { name: "Bruising", socId: "skin", frequency: "common" },
    { name: "Stomach irritation", socId: "gi", frequency: "common" },
    { name: "Tinnitus", socId: "ear", frequency: "uncommon" },
    { name: "Bronchospasm", socId: "respiratory", frequency: "uncommon" },
    { name: "Raised INR", socId: "investigations", frequency: "uncommon" },
  ],
  recommendations: [
    { id: "r1", tone: "red", title: "Emergency warning", detail: "Seek immediate care for black stools, vomiting blood, or a sudden severe headache." },
    { id: "r2", tone: "red", title: "Consult physician before combining", detail: "This pair is only used together for specific cardiac indications, under specialist supervision." },
    { id: "r3", tone: "amber", title: "Monitor INR closely", detail: "Check INR within 3–5 days of any change and then weekly until stable." },
    { id: "r4", tone: "amber", title: "Avoid alcohol", detail: "Alcohol compounds both gastric irritation and warfarin variability." },
    { id: "r5", tone: "green", title: "Add gastroprotection", detail: "A proton pump inhibitor markedly lowers GI bleeding risk if the pair must continue." },
  ],
  confidence: 94,
  sources: [
    { name: "DrugBank", records: 3, weight: 96 },
    { name: "DDInter", records: 2, weight: 91 },
    { name: "FAERS", records: 14304, weight: 88 },
    { name: "OpenFDA", records: 7, weight: 93 },
    { name: "PubMed", records: 128, weight: 90 },
  ],
};

const SIMVASTATIN_CLARITHROMYCIN: InteractionResult = {
  drugA: "Simvastatin",
  drugB: "Clarithromycin",
  severity: "contraindicated",
  headline: "Blocked clearance drives simvastatin to toxic muscle levels",
  summary:
    "Clarithromycin shuts down the liver enzyme that removes simvastatin from the body. Simvastatin levels can rise more than tenfold, and at those concentrations the drug starts to dissolve muscle tissue, releasing proteins that can clog the kidneys.",
  mechanism: [
    { id: "m1", kind: "drug", label: "Simvastatin + Clarithromycin", detail: "A CYP3A4 substrate paired with a strong CYP3A4 inhibitor." },
    { id: "m2", kind: "enzyme", label: "CYP3A4", detail: "Clarithromycin forms an inactive complex with the enzyme, halting metabolism." },
    { id: "m3", kind: "protein", label: "OATP1B1 / HMG-CoA reductase", detail: "Hepatic uptake saturates and systemic statin exposure rises sharply." },
    { id: "m4", kind: "interaction", label: "Pharmacokinetic inhibition", detail: "AUC increases roughly 10–12×, far beyond the therapeutic window." },
    { id: "m5", kind: "outcome", label: "Rhabdomyolysis", detail: "Muscle fibre breakdown releases myoglobin, threatening acute kidney injury." },
  ],
  socImpacts: [
    {
      socId: "musculoskeletal",
      severity: "contraindicated",
      explanation: "Toxic statin concentrations destabilise muscle cell membranes, causing widespread fibre breakdown.",
      symptoms: ["Severe muscle pain", "Weakness", "Dark cola-coloured urine"],
      evidence: ["DrugBank DB00641", "FAERS 3,910 reports", "PubMed 24334287"],
      confidence: 95,
    },
    {
      socId: "renal",
      severity: "major",
      explanation: "Myoglobin released from damaged muscle obstructs renal tubules and can trigger acute kidney injury.",
      symptoms: ["Reduced urine output", "Swelling", "Rising creatinine"],
      evidence: ["PubMed 23459229", "OpenFDA label"],
      confidence: 88,
    },
    {
      socId: "hepatobiliary",
      severity: "moderate",
      explanation: "Both drugs stress hepatocytes; transaminases commonly rise during co-administration.",
      symptoms: ["Nausea", "Right-upper-quadrant discomfort", "Jaundice"],
      evidence: ["DDInter DDI-0114"],
      confidence: 74,
    },
    {
      socId: "investigations",
      severity: "major",
      explanation: "Creatine kinase can exceed 10× the upper limit of normal within days.",
      symptoms: ["CK > 10× ULN", "Raised creatinine", "Myoglobinuria"],
      evidence: ["OpenFDA label", "PubMed 24334287"],
      confidence: 91,
    },
    {
      socId: "cardiac",
      severity: "moderate",
      explanation: "Clarithromycin prolongs the QT interval, and electrolyte shifts from kidney injury add to the risk.",
      symptoms: ["Palpitations", "Fainting", "Irregular heartbeat"],
      evidence: ["FAERS 480 reports"],
      confidence: 69,
    },
    {
      socId: "metabolism",
      severity: "minor",
      explanation: "Potassium and phosphate released from muscle can disturb electrolyte balance.",
      symptoms: ["Hyperkalaemia", "Muscle cramps"],
      evidence: ["PubMed 23459229"],
      confidence: 62,
    },
    {
      socId: "nervous",
      severity: "minor",
      explanation: "Headache and dizziness are frequently reported during combined exposure.",
      symptoms: ["Headache", "Dizziness", "Peripheral tingling"],
      evidence: ["FAERS 210 reports"],
      confidence: 55,
    },
  ],
  graph: {
    nodes: [
      { id: "simva", label: "Simvastatin", kind: "drug" },
      { id: "clari", label: "Clarithromycin", kind: "drug" },
      { id: "cyp3a4", label: "CYP3A4", kind: "protein" },
      { id: "oatp", label: "SLCO1B1", kind: "gene" },
      { id: "liver", label: "Liver", kind: "organ", socId: "hepatobiliary" },
      { id: "muscle", label: "Skeletal muscle", kind: "organ", socId: "musculoskeletal" },
      { id: "kidney", label: "Kidney", kind: "organ", socId: "renal" },
      { id: "rhabdo", label: "Rhabdomyolysis", kind: "effect", socId: "musculoskeletal" },
      { id: "aki", label: "Acute kidney injury", kind: "effect", socId: "renal" },
    ],
    edges: [
      { from: "clari", to: "cyp3a4", label: "inhibits" },
      { from: "simva", to: "cyp3a4", label: "substrate" },
      { from: "cyp3a4", to: "liver" },
      { from: "oatp", to: "liver", label: "uptake" },
      { from: "liver", to: "muscle", label: "systemic exposure" },
      { from: "muscle", to: "rhabdo" },
      { from: "rhabdo", to: "kidney", label: "myoglobin" },
      { from: "kidney", to: "aki" },
    ],
  },
  effectsA: [
    { name: "Muscle pain", socId: "musculoskeletal", frequency: "common" },
    { name: "Raised creatine kinase", socId: "investigations", frequency: "common" },
    { name: "Liver enzyme elevation", socId: "hepatobiliary", frequency: "uncommon" },
    { name: "Headache", socId: "nervous", frequency: "common" },
    { name: "Rhabdomyolysis", socId: "musculoskeletal", frequency: "rare" },
  ],
  effectsB: [
    { name: "Nausea", socId: "gi", frequency: "common" },
    { name: "Taste disturbance", socId: "nervous", frequency: "common" },
    { name: "QT prolongation", socId: "cardiac", frequency: "uncommon" },
    { name: "Liver enzyme elevation", socId: "hepatobiliary", frequency: "uncommon" },
    { name: "Headache", socId: "nervous", frequency: "common" },
  ],
  recommendations: [
    { id: "r1", tone: "red", title: "Do not combine", detail: "Suspend simvastatin for the duration of the clarithromycin course." },
    { id: "r2", tone: "red", title: "Emergency warning", detail: "Dark urine with severe muscle pain needs same-day medical assessment." },
    { id: "r3", tone: "amber", title: "Switch the antibiotic", detail: "Azithromycin does not meaningfully inhibit CYP3A4 and is usually a safe alternative." },
    { id: "r4", tone: "amber", title: "Check CK if symptomatic", detail: "Measure creatine kinase and renal function at the first sign of muscle pain." },
    { id: "r5", tone: "green", title: "Resume safely", detail: "Restart the statin 48 hours after the antibiotic course finishes." },
  ],
  confidence: 97,
  sources: [
    { name: "DrugBank", records: 4, weight: 98 },
    { name: "DDInter", records: 3, weight: 95 },
    { name: "FAERS", records: 4600, weight: 90 },
    { name: "OpenFDA", records: 9, weight: 96 },
    { name: "PubMed", records: 214, weight: 94 },
  ],
};

const LISINOPRIL_IBUPROFEN: InteractionResult = {
  drugA: "Lisinopril",
  drugB: "Ibuprofen",
  severity: "moderate",
  headline: "Opposing effects on kidney blood flow blunt blood-pressure control",
  summary:
    "Lisinopril relaxes the vessel leaving the kidney filter while ibuprofen constricts the vessel entering it. Together they can squeeze filtration pressure from both sides, raising blood pressure and potassium and reducing kidney performance.",
  mechanism: [
    { id: "m1", kind: "drug", label: "Lisinopril + Ibuprofen", detail: "An ACE inhibitor combined with a non-selective NSAID." },
    { id: "m2", kind: "enzyme", label: "ACE & COX-1/2", detail: "Angiotensin II production falls while renal prostaglandins are suppressed." },
    { id: "m3", kind: "protein", label: "Renin-angiotensin-aldosterone axis", detail: "Afferent vasoconstriction meets efferent vasodilation." },
    { id: "m4", kind: "interaction", label: "Pharmacodynamic antagonism", detail: "Glomerular filtration pressure drops and sodium is retained." },
    { id: "m5", kind: "outcome", label: "Reduced renal function & lost BP control", detail: "Creatinine and potassium rise; antihypertensive effect weakens." },
  ],
  socImpacts: [
    {
      socId: "renal",
      severity: "major",
      explanation: "Filtration pressure falls from both sides of the glomerulus, especially in dehydration or older age.",
      symptoms: ["Reduced urine output", "Ankle swelling", "Rising creatinine"],
      evidence: ["DrugBank DB00722", "PubMed 23299603"],
      confidence: 87,
    },
    {
      socId: "vascular",
      severity: "moderate",
      explanation: "Sodium and fluid retention offsets the antihypertensive effect by roughly 5 mmHg.",
      symptoms: ["Higher blood pressure readings", "Headache"],
      evidence: ["DDInter DDI-0209"],
      confidence: 80,
    },
    {
      socId: "metabolism",
      severity: "moderate",
      explanation: "Reduced aldosterone plus lower filtration lets potassium accumulate.",
      symptoms: ["Hyperkalaemia", "Muscle weakness", "Palpitations"],
      evidence: ["OpenFDA label", "FAERS 1,120 reports"],
      confidence: 76,
    },
    {
      socId: "gi",
      severity: "moderate",
      explanation: "Ibuprofen alone erodes gastric mucosa; risk climbs with age and duration.",
      symptoms: ["Indigestion", "Stomach pain", "Dark stools"],
      evidence: ["OpenFDA label"],
      confidence: 72,
    },
    {
      socId: "cardiac",
      severity: "minor",
      explanation: "Fluid retention can unmask or worsen existing heart failure.",
      symptoms: ["Breathlessness on exertion", "Swelling", "Weight gain"],
      evidence: ["PubMed 24297192"],
      confidence: 61,
    },
    {
      socId: "investigations",
      severity: "moderate",
      explanation: "Creatinine, eGFR and serum potassium all shift within one to two weeks.",
      symptoms: ["Creatinine +30%", "Potassium > 5.5 mmol/L"],
      evidence: ["DDInter DDI-0209"],
      confidence: 83,
    },
  ],
  graph: {
    nodes: [
      { id: "lis", label: "Lisinopril", kind: "drug" },
      { id: "ibu", label: "Ibuprofen", kind: "drug" },
      { id: "ace", label: "ACE", kind: "protein" },
      { id: "cox", label: "COX-1/2", kind: "protein" },
      { id: "ace_gene", label: "ACE gene", kind: "gene" },
      { id: "kidney", label: "Kidney", kind: "organ", socId: "renal" },
      { id: "vessels", label: "Vasculature", kind: "organ", socId: "vascular" },
      { id: "aki", label: "Renal impairment", kind: "effect", socId: "renal" },
      { id: "htn", label: "Loss of BP control", kind: "effect", socId: "vascular" },
    ],
    edges: [
      { from: "lis", to: "ace", label: "inhibits" },
      { from: "ace_gene", to: "ace" },
      { from: "ibu", to: "cox", label: "inhibits" },
      { from: "ace", to: "kidney", label: "efferent dilation" },
      { from: "cox", to: "kidney", label: "afferent constriction" },
      { from: "cox", to: "vessels" },
      { from: "kidney", to: "aki" },
      { from: "vessels", to: "htn" },
    ],
  },
  effectsA: [
    { name: "Dry cough", socId: "respiratory", frequency: "common" },
    { name: "Dizziness", socId: "nervous", frequency: "common" },
    { name: "Hyperkalaemia", socId: "metabolism", frequency: "uncommon" },
    { name: "Angioedema", socId: "immune", frequency: "rare" },
    { name: "Rising creatinine", socId: "renal", frequency: "uncommon" },
  ],
  effectsB: [
    { name: "Stomach irritation", socId: "gi", frequency: "common" },
    { name: "Rising creatinine", socId: "renal", frequency: "uncommon" },
    { name: "Fluid retention", socId: "vascular", frequency: "common" },
    { name: "Dizziness", socId: "nervous", frequency: "uncommon" },
    { name: "Rash", socId: "skin", frequency: "uncommon" },
  ],
  recommendations: [
    { id: "r1", tone: "amber", title: "Monitor renal function", detail: "Check creatinine and potassium 1–2 weeks after starting the NSAID." },
    { id: "r2", tone: "amber", title: "Stay hydrated", detail: "Dehydration is the trigger that turns this pair from tolerable into harmful." },
    { id: "r3", tone: "green", title: "Prefer paracetamol", detail: "For simple pain relief, paracetamol avoids the renal interaction entirely." },
    { id: "r4", tone: "green", title: "Keep courses short", detail: "Occasional NSAID use is generally tolerated in patients with healthy kidneys." },
  ],
  confidence: 86,
  sources: [
    { name: "DrugBank", records: 2, weight: 90 },
    { name: "DDInter", records: 2, weight: 87 },
    { name: "FAERS", records: 2140, weight: 79 },
    { name: "OpenFDA", records: 5, weight: 88 },
    { name: "PubMed", records: 74, weight: 85 },
  ],
};

const SERTRALINE_TRAMADOL: InteractionResult = {
  drugA: "Sertraline",
  drugB: "Tramadol",
  severity: "major",
  headline: "Serotonin accumulates while the seizure threshold falls",
  summary:
    "Both drugs raise serotonin in the brain — one by blocking its reuptake, the other by releasing more of it. The excess can tip into serotonin syndrome, and tramadol independently makes seizures more likely.",
  mechanism: [
    { id: "m1", kind: "drug", label: "Sertraline + Tramadol", detail: "Two serotonergic agents with overlapping CNS activity." },
    { id: "m2", kind: "enzyme", label: "CYP2D6", detail: "Sertraline inhibits CYP2D6, shifting tramadol toward its serotonergic parent form." },
    { id: "m3", kind: "protein", label: "SERT & 5-HT receptors", detail: "Reuptake blockade plus increased release floods the synapse." },
    { id: "m4", kind: "interaction", label: "Serotonergic synergy", detail: "Central serotonin tone rises sharply; analgesic effect paradoxically weakens." },
    { id: "m5", kind: "outcome", label: "Serotonin syndrome & seizures", detail: "Agitation, tremor, hyperthermia and convulsions can appear within hours." },
  ],
  socImpacts: [
    {
      socId: "nervous",
      severity: "major",
      explanation: "Excess synaptic serotonin drives tremor, clonus and hyperreflexia; tramadol lowers the seizure threshold.",
      symptoms: ["Tremor", "Muscle twitching", "Seizure", "Severe headache"],
      evidence: ["DrugBank DB00193", "FAERS 2,860 reports", "PubMed 26721325"],
      confidence: 93,
    },
    {
      socId: "psychiatric",
      severity: "major",
      explanation: "Agitation, confusion and hallucinations are the earliest signs of serotonin toxicity.",
      symptoms: ["Agitation", "Restlessness", "Confusion", "Insomnia"],
      evidence: ["DDInter DDI-0087", "FAERS 1,730 reports"],
      confidence: 89,
    },
    {
      socId: "cardiac",
      severity: "moderate",
      explanation: "Autonomic instability produces tachycardia and blood-pressure swings.",
      symptoms: ["Fast heartbeat", "Palpitations", "Blood pressure swings"],
      evidence: ["PubMed 26721325"],
      confidence: 75,
    },
    {
      socId: "gi",
      severity: "moderate",
      explanation: "Serotonin excess in the gut causes nausea, cramping and diarrhoea.",
      symptoms: ["Nausea", "Diarrhoea", "Abdominal cramps"],
      evidence: ["OpenFDA label"],
      confidence: 72,
    },
    {
      socId: "musculoskeletal",
      severity: "moderate",
      explanation: "Sustained clonus and rigidity can progress to muscle breakdown in severe cases.",
      symptoms: ["Muscle rigidity", "Clonus", "Myalgia"],
      evidence: ["PubMed 22359404"],
      confidence: 68,
    },
    {
      socId: "general",
      severity: "moderate",
      explanation: "Hyperthermia and profuse sweating mark the transition to a medical emergency.",
      symptoms: ["Fever", "Sweating", "Shivering"],
      evidence: ["FAERS 980 reports"],
      confidence: 70,
    },
    {
      socId: "blood",
      severity: "minor",
      explanation: "SSRIs impair platelet serotonin uptake, mildly increasing bleeding tendency.",
      symptoms: ["Easy bruising", "Nosebleeds"],
      evidence: ["PubMed 20520722"],
      confidence: 58,
    },
  ],
  graph: {
    nodes: [
      { id: "sert", label: "Sertraline", kind: "drug" },
      { id: "tram", label: "Tramadol", kind: "drug" },
      { id: "sertp", label: "SERT", kind: "protein" },
      { id: "cyp2d6", label: "CYP2D6", kind: "gene" },
      { id: "brain", label: "CNS", kind: "organ", socId: "nervous" },
      { id: "gut", label: "Enteric nerves", kind: "organ", socId: "gi" },
      { id: "ss", label: "Serotonin syndrome", kind: "effect", socId: "nervous" },
      { id: "seiz", label: "Seizure risk", kind: "effect", socId: "nervous" },
    ],
    edges: [
      { from: "sert", to: "sertp", label: "blocks reuptake" },
      { from: "sert", to: "cyp2d6", label: "inhibits" },
      { from: "tram", to: "cyp2d6", label: "substrate" },
      { from: "tram", to: "sertp", label: "increases release" },
      { from: "sertp", to: "brain" },
      { from: "sertp", to: "gut" },
      { from: "brain", to: "ss" },
      { from: "brain", to: "seiz" },
    ],
  },
  effectsA: [
    { name: "Nausea", socId: "gi", frequency: "common" },
    { name: "Insomnia", socId: "psychiatric", frequency: "common" },
    { name: "Tremor", socId: "nervous", frequency: "uncommon" },
    { name: "Bruising", socId: "blood", frequency: "uncommon" },
    { name: "Sexual dysfunction", socId: "reproductive", frequency: "common" },
  ],
  effectsB: [
    { name: "Nausea", socId: "gi", frequency: "common" },
    { name: "Dizziness", socId: "nervous", frequency: "common" },
    { name: "Constipation", socId: "gi", frequency: "common" },
    { name: "Seizure", socId: "nervous", frequency: "rare" },
    { name: "Tremor", socId: "nervous", frequency: "uncommon" },
    { name: "Respiratory depression", socId: "respiratory", frequency: "rare" },
  ],
  recommendations: [
    { id: "r1", tone: "red", title: "Emergency warning", detail: "Fever with tremor, rigidity or confusion is serotonin syndrome until proven otherwise — call emergency services." },
    { id: "r2", tone: "red", title: "Consult physician", detail: "Do not start tramadol on an SSRI without prescriber review." },
    { id: "r3", tone: "amber", title: "Use the lowest effective dose", detail: "Risk scales with tramadol dose; avoid exceeding 200 mg/day when combined." },
    { id: "r4", tone: "amber", title: "Avoid alcohol and sedatives", detail: "Additive CNS depression compounds confusion and respiratory risk." },
    { id: "r5", tone: "green", title: "Safer analgesic options", detail: "Paracetamol or a topical NSAID avoids the serotonergic pathway." },
  ],
  confidence: 91,
  sources: [
    { name: "DrugBank", records: 3, weight: 93 },
    { name: "DDInter", records: 2, weight: 90 },
    { name: "FAERS", records: 5570, weight: 86 },
    { name: "OpenFDA", records: 6, weight: 92 },
    { name: "PubMed", records: 96, weight: 89 },
  ],
};

const METFORMIN_LEVOTHYROXINE: InteractionResult = {
  drugA: "Metformin",
  drugB: "Levothyroxine",
  severity: "minor",
  headline: "Thyroid replacement can nudge glucose control, but the pair is routinely used",
  summary:
    "Thyroid hormone speeds up how quickly the body handles sugar, so blood-glucose readings may drift when a dose changes. Metformin can also slightly lower TSH. Neither effect is dangerous — the two are prescribed together every day.",
  mechanism: [
    { id: "m1", kind: "drug", label: "Metformin + Levothyroxine", detail: "An insulin sensitiser alongside thyroid hormone replacement." },
    { id: "m2", kind: "enzyme", label: "AMPK / deiodinases", detail: "Metformin activates AMPK; thyroid hormone alters hepatic glucose output." },
    { id: "m3", kind: "protein", label: "TSH receptor", detail: "Metformin modestly suppresses TSH in treated patients." },
    { id: "m4", kind: "interaction", label: "Mild pharmacodynamic overlap", detail: "Glycaemic targets may need small adjustments after thyroid dose changes." },
    { id: "m5", kind: "outcome", label: "Monitoring, not avoidance", detail: "Routine TSH and HbA1c checks are sufficient." },
  ],
  socImpacts: [
    {
      socId: "endocrine",
      severity: "minor",
      explanation: "Metformin can lower measured TSH without changing free T4, which may look like over-replacement.",
      symptoms: ["Low TSH on testing", "No clinical symptoms in most patients"],
      evidence: ["PubMed 21430032", "DDInter DDI-0402"],
      confidence: 74,
    },
    {
      socId: "metabolism",
      severity: "minor",
      explanation: "Thyroid hormone increases glucose turnover, so glycaemic control may shift after a dose change.",
      symptoms: ["Blood glucose variability", "Occasional HbA1c drift"],
      evidence: ["OpenFDA label"],
      confidence: 66,
    },
    {
      socId: "gi",
      severity: "minor",
      explanation: "Metformin's own gastrointestinal effects are unchanged by levothyroxine.",
      symptoms: ["Nausea", "Diarrhoea", "Metallic taste"],
      evidence: ["OpenFDA label"],
      confidence: 60,
    },
    {
      socId: "investigations",
      severity: "minor",
      explanation: "Expect small movements in TSH and HbA1c rather than clinically important changes.",
      symptoms: ["TSH shift", "HbA1c drift"],
      evidence: ["PubMed 21430032"],
      confidence: 70,
    },
  ],
  graph: {
    nodes: [
      { id: "met", label: "Metformin", kind: "drug" },
      { id: "levo", label: "Levothyroxine", kind: "drug" },
      { id: "ampk", label: "AMPK", kind: "protein" },
      { id: "tshr", label: "TSHR", kind: "gene" },
      { id: "thyroid", label: "Thyroid", kind: "organ", socId: "endocrine" },
      { id: "liver", label: "Liver", kind: "organ", socId: "hepatobiliary" },
      { id: "glu", label: "Glucose variability", kind: "effect", socId: "metabolism" },
    ],
    edges: [
      { from: "met", to: "ampk", label: "activates" },
      { from: "met", to: "tshr", label: "modulates" },
      { from: "tshr", to: "thyroid" },
      { from: "levo", to: "thyroid", label: "replaces T4" },
      { from: "ampk", to: "liver" },
      { from: "liver", to: "glu" },
      { from: "thyroid", to: "glu" },
    ],
  },
  effectsA: [
    { name: "Diarrhoea", socId: "gi", frequency: "common" },
    { name: "Metallic taste", socId: "nervous", frequency: "uncommon" },
    { name: "Vitamin B12 deficiency", socId: "metabolism", frequency: "uncommon" },
    { name: "Lactic acidosis", socId: "metabolism", frequency: "rare" },
  ],
  effectsB: [
    { name: "Palpitations", socId: "cardiac", frequency: "uncommon" },
    { name: "Insomnia", socId: "psychiatric", frequency: "uncommon" },
    { name: "Weight change", socId: "metabolism", frequency: "common" },
    { name: "Hair thinning", socId: "skin", frequency: "uncommon" },
  ],
  recommendations: [
    { id: "r1", tone: "green", title: "Safe to combine", detail: "This pair is standard practice for co-existing diabetes and hypothyroidism." },
    { id: "r2", tone: "green", title: "Separate doses by 4 hours", detail: "Take levothyroxine on an empty stomach in the morning for reliable absorption." },
    { id: "r3", tone: "amber", title: "Recheck TSH after changes", detail: "Repeat TSH 6–8 weeks after any metformin or levothyroxine dose change." },
  ],
  confidence: 78,
  sources: [
    { name: "DrugBank", records: 1, weight: 76 },
    { name: "DDInter", records: 1, weight: 74 },
    { name: "FAERS", records: 320, weight: 62 },
    { name: "OpenFDA", records: 4, weight: 80 },
    { name: "PubMed", records: 31, weight: 77 },
  ],
};

export const SAMPLE_INTERACTIONS: InteractionResult[] = [
  WARFARIN_ASPIRIN,
  SIMVASTATIN_CLARITHROMYCIN,
  LISINOPRIL_IBUPROFEN,
  SERTRALINE_TRAMADOL,
  METFORMIN_LEVOTHYROXINE,
];

export const INTERACTION_INDEX = new Map(
  SAMPLE_INTERACTIONS.map((i) => [key(i.drugA, i.drugB), i]),
);

export const FEATURED_PAIRS: Array<{ a: string; b: string; severity: Severity }> = SAMPLE_INTERACTIONS.map(
  (i) => ({ a: i.drugA, b: i.drugB, severity: i.severity }),
);

export const pairKey = key;
